# This is a basic workflow to help you get started with Actions

name: CVE and Docs update

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup MySQL Tuner repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pwd
          cd build
          pwd
          sudo bash ./installStaff.sh

      - name: Update CVE and docs
        run: |
          pwd
          cd ..
          pwd
          sudo bash ./build/updateStaff.sh

      # Runs a single command using the runners shell
      - name: Commit CVE result to repo
        run: |
          git config --global user.name "Jean-Marie Renouard"
          git config --global user.email "jmrenouard@gmail.com"
          git add .
          git commit -m "Updates CVE and docs (via Actions) - $(date +'%Y-%m-%d')"
          git push